# Generated by Django 5.1.4 on 2025-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('rose', 'Розы'), ('tulip', 'Тюльпаны'), ('chrysanthemum', 'Хризантемы')], max_length=20)),
                ('color', models.CharField(choices=[('red', 'Красные'), ('pink', 'Розовые'), ('white', 'Белые'), ('yellow', 'Жёлтые')], max_length=20)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
